### ISSUE TITLE
wordpress inline embed not working

### ISSUE THREAD

**Issue by nimatris** [calcom/wp-plugin#12]
When I use the shortcode, it shows a blank page. 
The type 2 button for the popup works. 
Also, if I copy the html inline embed it doesn't show anything.

Any ideas? Might be a conflict with my theme (one page express)?

Thank you!

This is the code that is shown on the source file for the empty page:
 
<img width="791" alt="Bildschirmfoto 2024-03-14 um 10 31 00" src="https://github.com/calcom/wp-plugin/assets/1642969/95280759-de03-4a0f-9c5f-2485c199b482">

**Comment by AdamBorealis** [comment]
Hoping to get more eyes on this, as this was noted almost a year ago here:
https://wordpress.org/support/topic/uncaught-referenceerror-cal-is-not-defined/

I still get marketing emails, but can't use the plugin until it actually works.  ;)

**Comment by zomars** [comment]
Is it only the inline embed that doesn't work? Can you provide an example link? Sounds like the head scripts aren't being run before the shortcode.

**Comment by nimatris** [comment]
Hey Omar, it is the only that I have tried so far. 
This is the page, but currently I use the type 2 so that it is functional for my clients:
https://www.jonathanklodt.com/book-a-60-min-call/

**Comment by milospuac** [comment]
@hariombalhara @zomars what is the verdict here?

**Comment by zomars** [comment]
> Hey Omar, it is the only that I have tried so far. This is the page, but currently I use the type 2 so that it is functional for my clients: [jonathanklodt.com/book-a-60-min-call](https://www.jonathanklodt.com/book-a-60-min-call/)

This seems to be resolved:

<img width="1728" alt="image" src="https://github.com/calcom/wp-plugin/assets/3504472/aeca10d0-f702-48f7-81c0-86166ff10915">

**Comment by nimatris** [comment]
No, it's not 🫤 
I just had the plugin shortcode set to type 2, which shows the button. That worked all the time, but the inline embed with type 1 still doesn't work and shows an empty page. Just tried it again...

<img width="1421" alt="Bildschirmfoto 2024-05-07 um 15 06 40" src="https://github.com/calcom/wp-plugin/assets/1642969/aebb8417-9f6d-490c-a3dd-af76ee28a0e7">
As you can see, you can see… nothing. ☝️

**Comment by CodeShakingSheep** [comment]
Hi @nimatris,
@zomars is right that this issue has been resolved in https://github.com/calcom/wp-plugin/pull/4 . The issue is just that there hasn't been a release of a new plugin version since this fix. 

I can see from the code you posted in your initial post that it's the old code from before the fix. So, as a workaround instead of installing the cal.com plugin directly in WordPress you could download the ZIP file from this repository and upload it manually to your WordPress site.

**Comment by nimatris** [comment]
Thank you @CodeShakingSheep and @zomars for your support! 
Somehow I can't find the zip file here on github (pardon my ignorance, new to this platform) - could you provide me with a link where to download it? Thank you again!

**Comment by nimatris** [comment]
Thank you @CodeShakingSheep and @zomars!
I tried that and now see that I have Version 1.0.1 instead of previously Version 1.0.0 installed. 
But it still shows an empty page. Maybe it is a problem with my template... 
I'll just continue using the popup button, that seems to work for most devices and browsers without messing up the responsive design like the iFrame does.

**Comment by CodeShakingSheep** [comment]
> Thank you @CodeShakingSheep and @zomars! I tried that and now see that I have Version 1.0.1 instead of previously Version 1.0.0 installed. But it still shows an empty page. Maybe it is a problem with my template... I'll just continue using the popup button, that seems to work for most devices and browsers without messing up the responsive design like the iFrame does.

As the change is in JS you need to empty your cache for the new script to load. If you use a chrome based browser you can do that by hitting "F12", then right click on the reload button of your page and then click "Empty cache and hard reload". If you use a WordPress caching plugin you should empty its cache too. Let me know if that works.

**Comment by nimatris** [comment]
Thank you @CodeShakingSheep for that tip, still didn't work, also tried the page in a different browser.

**Comment by Ys-sudo** [comment]
[#13 ](https://github.com/calcom/wp-plugin/pull/13)- this one fixed it you can apply it manually to the file and the inline option will work :)
